### ISSUE TITLE
cy.waitFor change of attribute/label

### ISSUE THREAD

**Issue by Brestachan** [dominikwilkowski/cypress-waitfor#2]
Hi!
I'm not sure if this is something that the plugin is capable of doing, but it could be a change request of sorts if not. 
Anyway, I have a table and in one of the cells the label is changing (going from "Downloading in progress" to "Complete"). So, when I'm using this plugin, I only get to wait for the element, in this case a certain cell in the table, to be visible, which is momentarily, but it would be great if the plugin would work with labels and other attributes as well.
Something like:
`cy.waitFor('#tableName > :nth-child(1) > label).contains("Complete")`

The plugin itself is super useful, don't get me wrong, and I used it in many occasions, but this is something that would be great addition to the already pretty good plugin.

**Comment by dominikwilkowski** [comment]
This is a great idea but out of scope for this plugin. I feel like cypress has something built in for this though?
