### ISSUE TITLE
Cypress.Commands.add() cannot create a new command named waitFor because that name is reserved internally by Cypress.

### ISSUE THREAD

**Issue by kodriscollics** [dominikwilkowski/cypress-waitfor#3]
After upgrading to Cypress 10 (10.5.0) I now get the following error when running tests that use cypress-waitFor:

> Cypress.Commands.add() cannot create a new command named waitFor because that name is reserved internally by Cypress.

I have to comment out; import 'cypress-waitfor' from the commands file. However, Cypress then complains that "tries" is not a valid option and I have to comment out the "tries: 200" option

@dominikwilkowski ... I love this Cypress addon. It has been working great for me using Cypress 9.x. There may now be an incompatibility with Cypress 10 that needs adjusting? Or a configuration issue with the way it needs to work with Cypress 10 perhaps (though I haven't been able to figure that out yet if that is the case).

**Comment by jacekk** [comment]
Same here :cry:

**Comment by dominikwilkowski** [comment]
Thanks for reporting. I'll look into it

**Comment by kodriscollics** [comment]
@dominikwilkowski just checking to see if you've had a chance to look into this yet. I have a lot of tests failing because this isn't working. I'd need to remove the waitFor everywhere and replace it with something else (which I'd rather not do as waitFor is easy and works so well.) Thanks!

**Comment by dominikwilkowski** [comment]
Hey @kodriscollics 
I haven't had the time as I am traveling for work this week but from what I can see I'm guessing I will have to rename the package. Any suggestions as to what a good name for this could be?

**Comment by kodriscollics** [comment]
@dominikwilkowski no worries. I know how busy and chaotic life can be sometimes.

My first thought was "waitOn" but then I realized that could mean wait while on a selector.
My second thought was "waitForSelector".
Also, "pauseFor" could work.

Thanks!

**Comment by dominikwilkowski** [comment]
I'll see what I can do tonight (it's 4:30pm here)

**Comment by dominikwilkowski** [comment]
This package is now published under [`cypress-waitforselector`](https://www.npmjs.com/package/cypress-waitforselector) to the registry

**Comment by jacekk** [comment]
@dominikwilkowski After the rename, the README example looks kinda silly :wink: 

```js
cy.waitForSelector(() => {
      const localData = localStorage.getItem('myData');
      return localData !== null;
});
```

**Comment by dominikwilkowski** [comment]
yeah ... naming is hard ;)

**Comment by kodriscollics** [comment]
Great work @dominikwilkowski ... thank you!

I uninstalled the cypress-waitfor package, then installed the new cypress-waitforselector package, renamed all my cy.waitFor statements to cy.waitForSelector and changed the import statement in the commands.js file to import 'cypress-waitforselector' and it works great.

Thanks again!
